### ISSUE TITLE
"Found duplicate ID" error when two resources implement the same strategy

### ISSUE THREAD

**Issue by axelbdt** [team-alembic/ash_authentication_phoenix#108] opened 2023-02-07 09:34 UTC
Hi, I tried adding a second resource implementing the password strategy, to test the autofocus fix.
I got the following error when accessing the sign-in route:
```
found duplicate ID "get-by-subject-password-register-with-password" for component AshAuthentication.Phoenix.Components.Password.RegisterForm when rendering template
```
After some digging and perplexity, I found this fix:
```elixir
# admin.ex
strategies do
  get_by_subject_action_name :whatever  # <- add this line
  
  password do
  ...
  end
end
```

Maybe a dedupe mechanism should be implemented by default or the necessity of this line should be documented.

**Comment by zachdaniel** [comment] 2023-02-07 13:00
@axelbdt is it letting you specify two password strategies with the same name?
```elixir
password do

end

password do

end
```

by not specifying a name its getting the default of `:password`. If so, then we are missing a validation.

**Comment by axelbdt** [comment] 2023-02-08 09:38
Yes, I am able to specify two `password` strategies with default name.
I can specify them in the same resource, or in two different resources: in both cases, the code compiles, but will cause error `found duplicate ID...`when accessing the sign-in route.

**Comment by zachdaniel** [comment] 2023-02-08 12:28
Got it :) well we should fix both of those behaviors then. Thanks so much for confirming that info and for the report :)

**Comment by Morzaram** [comment] 2023-10-21 18:38
Also encountered this issue, I think in the meantime we can update the docs or have a section in the docs that mentions implementing multiple auth resources. 

I see there's a PR that once it's completed and merged seems to implement all we need to have this functional without duplicating login html

https://github.com/team-alembic/ash_authentication_phoenix/pull/310

**Comment by BryanJBryce** [comment] 2023-10-24 23:34
@Morzaram Is it possible then to have one auth resource with a tenant and one without? That would be nice to have a separate super admin resource from tenant users.

**Comment by Morzaram** [comment] 2023-10-25 06:09
As in you want a page so you can login as any tenant type, much like we have now? I think I can make that work, but no promises, I'm quite new haha

**Comment by jimsynz** [comment] 2023-10-25 21:12
So I just tried to put multiple strategies in a resource with the same name, and they're caught by one of our transformer validations:

```
== Compilation error in file test/support/example/user.ex ==
** (Spark.Error.DslError) [Example.User]
 authentication -> strategies:
  Strategy names must be unique.

  * strategy `:password` is repeated twice.
    (spark 1.1.48) lib/spark/dsl/extension.ex:626: Spark.Dsl.Extension.raise_transformer_error/2
    (elixir 1.15.6) lib/enum.ex:4830: Enumerable.List.reduce/3
    (elixir 1.15.6) lib/enum.ex:2564: Enum.reduce_while/3
    (stdlib 5.1) erl_eval.erl:746: :erl_eval.do_apply/7
    (stdlib 5.1) erl_eval.erl:1026: :erl_eval.expr_list/7
    (stdlib 5.1) erl_eval.erl:456: :erl_eval.expr/6
    (stdlib 5.1) erl_eval.erl:1026: :erl_eval.expr_list/7
    (stdlib 5.1) erl_eval.erl:456: :erl_eval.expr/6
```

Are you using an older version of AshAuthentication?

**Comment by zachdaniel** [comment] 2023-10-25 21:13
The issue is multiple strategies with the same name in different resources, not the same one.

**Comment by jimsynz** [comment] 2023-10-25 21:13
> Yes, I am able to specify two `password` strategies with default name. I can specify them in the same resource, or in two different resources: in both cases, the code compiles, but will cause error `found duplicate ID...`when accessing the sign-in route.

Seems like it's both.

**Closed** 2023-10-25 21:36 UTC
